x-default-accrobotics-isaaclab-environment: &default-accrobotics-isaaclab-environment
  - OMNI_KIT_ALLOW_ROOT=1

x-default-accrobotics-isaaclab-deploy: &default-accrobotics-isaaclab-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  accrobotics-isaaclab:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE}
        - DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH_ARG=${DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH}
    image: accrobotics-isaaclab
    container_name: accrobotics-isaaclab
    volumes:
      - type: bind
        source: ../
        target: ${DOCKER_ISAACLAB_EXTENSION_TEMPLATE_PATH}
    network_mode: host
    environment: *default-accrobotics-isaaclab-environment
    deploy: *default-accrobotics-isaaclab-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
